# Site settings
title: A blog about personal developer
description: A blog about personal developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: B@TULGA Developer
user_description: About experience and skills
user_title: Software Developer
email: battulga.l@gmail.com
twitter_username: battulgal
github_username:  battulga-l
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
